"""empty message

Revision ID: 1214e9f404d4
Revises: 34c1db06c02c
Create Date: 2019-01-30 13:52:19.338225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1214e9f404d4'
down_revision = '34c1db06c02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('chapter_name', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dictionary'], ['dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_chapter_name'), 'chapter', ['chapter_name'], unique=True)
    op.create_index(op.f('ix_chapter_created_datetime'), 'chapter', ['created_datetime'], unique=False)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('translation', sa.String(length=64), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_created_datetime'), 'word', ['created_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_created_datetime'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_chapter_created_datetime'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_chapter_name'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
